CREATE TABLE IF NOT EXISTS central_admin (
    id integer PRIMARY KEY CHECK (id = 1),
    username text NOT NULL,
    password_hash text NOT NULL
);
CREATE TABLE IF NOT EXISTS central_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL CHECK (length(trim(name)) > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS central_category_name ON central_categories (lower(name));
CREATE TABLE IF NOT EXISTS central_materials (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(160) NOT NULL,
    description varchar(2000) NOT NULL DEFAULT '',
    category_id integer NOT NULL REFERENCES central_categories(id) ON DELETE RESTRICT,
    filename varchar(180) NOT NULL,
    blob_path text NOT NULL UNIQUE,
    size_bytes bigint NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 52428800),
    published boolean NOT NULL DEFAULT false,
    downloads bigint NOT NULL DEFAULT 0,
    legacy_key text UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS central_sessions (
    token_hash text PRIMARY KEY,
    auth_version text NOT NULL,
    expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS central_login_limits (
    key text PRIMARY KEY,
    attempts integer NOT NULL DEFAULT 0,
    window_start timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS central_uploads (
    id uuid PRIMARY KEY,
    pathname text NOT NULL UNIQUE,
    filename varchar(180) NOT NULL,
    owner_hash text NOT NULL,
    expected_size bigint NOT NULL CHECK (expected_size > 0 AND expected_size <= 52428800),
    expires_at timestamptz NOT NULL,
    consumed boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS central_blob_cleanup (
    pathname text PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now()
);
